//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2G7_PVFAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoesBusinessIn
    {
        public int TerritoryID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<decimal> Revenue { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SalesTerritory SalesTerritory { get; set; }
    }
}
